spin_manifest_version = "1"
authors = ["Christoph Voigt <voigt.christoph@gmail.com>"]
description = "The personal website of Saul O'Driscol"
name = "sauls-website"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.0.2/spin_static_fs.wasm", digest = "sha256:65456bf4e84cf81b62075e761b2b0afaffaef2d0aeda521b245150f76b96421b" }
id = "sauls-website"
files = [ { source = "static", destination = "/" } ]
[component.trigger]
route = "/..."
[component.build]
command = "hugo -s ../ -d ./spin/static/ --minify --baseURL 'https://saul.com/'"
